#!/bin/bash
#Cristian Villegas
if [ $EUID -ne 0 ]
then
	echo "This script must be run as root (admin)"
	exit 1
fi
clear
REGEX='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
echo -n "Primera direccion IP para DNS:"
read DNS0
echo -n "Segunda direccion IP para DNS:"
read DNS1

if [[ $DNS0 =~ $REGEX ]] && [[ $DNS1 =~ $REGEX ]]
then
	echo "# Generated by NetworkManager" >> /etc/resolv.conf
	echo "search fjeclot.net" >> /etc/resolv.conf
	echo "nameserver $DNS0" >> /etc/resolv.conf
	echo "nameserver $DNS1" >> /etc/resolv.conf
else
	echo "Variable incorrecta. Adios"
	exit 1
fi
exit 0
